#!/usr/bin/env bash

# Update the package list
apt-get update

# Install Nginx
apt-get install -y nginx

# Create a custom HTML file to serve
echo "Hello World!" > /var/www/html/index.html

# Start Nginx using the init script (since systemctl can't be used)
service nginx start

# Ensure Nginx will start on boot
update-rc.d nginx defaults
