#!/usr/bin/env bash
#This script installs nginx
# Install nginx

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx restart
