#!/usr/bin/env bash
# Installs HAProxy

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

echo "
frontend alfred
    bind *:80
    mode http
    default_backend app

backend app
    balance roundrobin
    server 422504-web-01 100.26.132.5:80 check
    server 422504-web-02 18.210.15.61:80 check" >>/etc/haproxy/haproxy.cfg

sudo service haproxy restart
